version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/Simplybyte_calculator-new
hooks:
  
  BeforeInstall:
    - location: scripts/install.sh
      timeout: 300
      runas: ec2-user
  AfterInstall:
    - location: scripts/start.sh
      timeout: 300
      runas: ec2-user
